[package]
name = "syozin"
version = "0.1.0"
authors = ["dehachi <59132212+dehachi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"
itertools = "0.10.0"